name: publish-release

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: ${{ github.repository == 'bsmth/follow-xrefs' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        with:
          persist-credentials: false
        uses: actions/checkout@v5

      - name: Release Please
        uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        if: ${{ steps.release.outputs.release_created }}
        run: npm install

      - name: Publish VSCE
        if: ${{ steps.release.outputs.release_created }}
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
