on:
  release:
    types:
      - created

jobs:
  publish:
    if: ${{ github.repository == 'bsmth/follow-xrefs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
